// SPDX-License-Identifier: MIT
// include/bc1_shader.h
// Minimal placeholder shader header to satisfy compilation.
// Replace the arrays below with real SPIR-V data generated by your shader build pipeline.

#ifndef BC1_SHADER_H
#define BC1_SHADER_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Example symbol names — adjust only if your code expects different names.
   These declarations provide the linker-visible symbols used by bc_emulate.c.
   For real behavior replace the arrays with actual SPIR-V uint32_t data and sizes. */

extern const uint32_t bc1_spv[];
extern const size_t bc1_spv_size;

/* Provide weak default definitions so linking succeeds even if object providing
   real data is absent. Several toolchains allow weak definitions in headers via
   attributes; to keep this universally compilable we provide external declarations
   only and supply a small noop object below when needed. */

#ifdef BC1_SHADER_HEADER_DEFINE_DEFAULTS
/* If you need the header to also define a default object (less common),
   define BC1_SHADER_HEADER_DEFINE_DEFAULTS before including this header in exactly one
   C file, e.g., by adding -DBC1_SHADER_HEADER_DEFINE_DEFAULTS to that file's compile flags. */

const uint32_t bc1_spv[] = { 0x07230203u }; /* minimal placeholder SPIR-V word (invalid as real shader) */
const size_t bc1_spv_size = sizeof(bc1_spv);
#endif

#ifdef __cplusplus
}
#endif

#endif /* BC1_SHADER_H */
